### ISSUE TITLE
Support for @aspnet/signalr 1.0.0-preview1-update1

### ISSUE THREAD

**Issue by alexmg** [sketch7/signalr-client#14]
The ASP.NET team have renamed the SignalR TS client package to `@aspnet/signalr` and have released version `1.0.0-preview1-update1` to accompany the latest `1.0.0-preview1-final` release of the `Microsoft.AspNetCore.SignalR` NuGet package.

I testing updating to the new package and there doesn't appear to be any breaking changes aside from changing the package name and fixing the imports.

I'm happy to submit a PR if this would be helpful.

**Comment by claylaut** [comment]
Hi @alexmg,

Sure, you can open a pr and will review it :) 

kindly follow the contribution guidelines:
https://github.com/sketch7/signalr-client/blob/master/docs/DEVELOPMENT-WORKFLOW.md#preparation-for-release

Thanks!

**Comment by alexmg** [comment]
Thanks for the quick response @claylaut. 😃 

Reading the contribution guidelines it suggests performing the version bump in the feature branch prior to submitting a PR. Considering the package is not yet at `1.0` are you happy with bumping the minor version to update the package to `0.5.0`?

**Comment by claylaut** [comment]
Yes please, you should bump it as minor `v0.5.0` (since I would like to be considered as a breaking change).

**Comment by alexmg** [comment]
I have submitted the PR but the build failed with `cb() never called!` error. A number of bitHound issues have also been found as part of the build. I suspect this is actually a result of the process never having been run before and not something specific to the changes in the PR. I'll let you decide how best to proceed.

**Comment by claylaut** [comment]
@alexmg, I ve merged it but for now, I didn't release it since when I've tested with a previous server version (alpha2) it didnt connect.

error:
`Error: Failed to start the connection. SyntaxError: Unexpected token < in JSON at position 0`

Hopefully during the weekend, I will have some time to try it out with an updated server, since i need to update to .NET CORE 2.1 preview + download the new preview VS.

Did you manage to connect to a server?

**Comment by claylaut** [comment]
Closing issue now its updated to rc1.
