### ISSUE TITLE
Unable to connect with hub

### ISSUE THREAD

**Issue by TheAifam5** [sketch7/signalr-client#28]
Hey,
I noticed that the library does not try to connect with an external SignalR server, also after multiple calls to "connect" function of "HubConnection".

I can't provide any info since the library does not print anything and do nothing.

Regards,
TheAifam5

**Comment by claylaut** [comment]
Hi @TheAifam5 ,

This sounds more like a server issue rather than a client issue. 

Can you please tell me more information about:
* Sketch7 signalr client version: 
* SignalR Server NuGet Package Name: 
* SignalR Server NuGet Package Version:
* Do you have signalr on multi cluster server:
* Are you using any LB :

Do you have any client logs and server logs?

Just to answer your question, it works with an external signalr server without any issues.

**Comment by TheAifam5** [comment]
Hey,

I implemented manually the connection with the SignalR server using a @aspnet/signalr library and works. Using this library I was not able to connect also when I tried “connect” or “connectAll”.

The server is just simple dotnet 2.1 webapi with some SignalR hubs, its a standalone server (no SPA integration).

There is no logs on the client or server side, as I said - in the library there is no possibilities to set the LogLevel using the configuration, so I debugged it, jumpes where the SignalR Hub is initialized and manually changed the LogLevel value to 0, but I’ve got only the message that is connecting using binary mode.

Everything is currently local hosted, SSL disabled on both sides.

Regards,
TheAifam5

**Comment by claylaut** [comment]
Did you create an instance of `HubConnectionFactory`? 
This ideally will be registered into your DI (if you're using any library) or you can create instance manually.

Please note that the below code is a very raw sample:
 
Step 1:
 - Register Hubs in the `HubConnectionFactory`
```ts
import { HubConnectionFactory, HubConnection } from "@ssv/signalr-client";

const hubFactory = new HubConnectionFactory();
hubFactory.create(
	{ key: "hero", endpointUri: "/hero" },  
	{ key: "user", endpointUri: "http://localhost:62551/real-time/user" }
);
```

Step2:
- Get Hub by Key
- Connect
- subscribe for `on` 
```ts
const hubConnection = hubFactory.get<HeroHub>("hero");
const hubConnection$$ = hubConnection.connect().subscribe(() => {
	console.log(`connected!`);
});

const data$$ = hubConnection.on<string>("Send").subscribe(val => {
	console.log(`send :: data received >>>`, val);
});
```
Important note: if you dont `subscribe` for any particular observable, the observable wont be triggered since it will be a cold observable.

Hope this helps!

If you can share your sample project on github or any open source let me know so I can see how you are using the library.

Side note: We use this library at work for Production env. :)

**Comment by TheAifam5** [comment]
@claylaut I'm gonna try it right now. One more chance :D

Oh wow... now I understood my problem :D I was testing the "subscribe" on "connect" but... ah, nvm.

Btw.. It's really good example, would be nice to see that in the documentation. Actually there is nothing about "subscribe" on "connect".

**Comment by claylaut** [comment]
I m glad, I've managed to help you :) if you have any other questions do not hesitate to ask.

Thanks for your feedback!! I really appreciate it! I will update the documentation straight away.

Don't forget to star the project 😃
