### ISSUE TITLE
How do we test?

### ISSUE THREAD

**Issue by NullVoxPopuli** [sketch7/signalr-client#35]
Let's say I'm doing the type of test just below end-to-end tests, where I'm mocking the backend.

How do I tell my test environment to have a fake signalr server that I can control the responses with?

fwiw, all socket communication uses http://jsonapi.org/ format messages, so I am not worried with frontend and backend getting out of sync and causing issues that tests wouldn't catch. (frontend team is also regularly communicating with backend team, and there isn't much reason to change the api's data model)

**Comment by stephenlautier** [comment]
Not entirely sure if I understood you correctly, but mocking signalr from the frontend is that good for you? or you need to fake it from the server itself?

**If from the client**, we are doing a mock signalr backend (which I'd like to publish separately but its not 100% ready yet), which we use for unit tests which you find [here](https://github.com/sketch7/signalr-client/blob/master/src/testing/mock-hub.ts#L48) and usages in [tests ](https://github.com/sketch7/signalr-client/blob/master/src/hub-connection.connection.spec.ts#L223).
Currently, we have connection stuff only, but its simple code and you can fairly simple add fake for `on` or so. The tricky part might be to replace the actual implementation if its not running in tests since you might not have jest/jasmine to replace with fake.

**If you need from server** not entirely sure what you have in mind, but you can perhaps replace your Hubs or perhaps their dependency service (or so) with fake code; but might be best to ask aspnet signalr themselves if you dont like what i suggest

hope it helps!
